// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface AppStateSyncKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.AppStateSyncKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .binary.AppStateSyncKeyId keyIds = 1;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.AppStateSyncKeyId>
      getKeyIdsList();
  /**
   * <code>repeated .binary.AppStateSyncKeyId keyIds = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.AppStateSyncKeyId getKeyIds(int index);
  /**
   * <code>repeated .binary.AppStateSyncKeyId keyIds = 1;</code>
   */
  int getKeyIdsCount();
  /**
   * <code>repeated .binary.AppStateSyncKeyId keyIds = 1;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.AppStateSyncKeyIdOrBuilder>
      getKeyIdsOrBuilderList();
  /**
   * <code>repeated .binary.AppStateSyncKeyId keyIds = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.AppStateSyncKeyIdOrBuilder getKeyIdsOrBuilder(
      int index);
}
