// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface AppStateSyncKeyShareOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.AppStateSyncKeyShare)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .binary.AppStateSyncKey keys = 1;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.AppStateSyncKey>
      getKeysList();
  /**
   * <code>repeated .binary.AppStateSyncKey keys = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.AppStateSyncKey getKeys(int index);
  /**
   * <code>repeated .binary.AppStateSyncKey keys = 1;</code>
   */
  int getKeysCount();
  /**
   * <code>repeated .binary.AppStateSyncKey keys = 1;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.AppStateSyncKeyOrBuilder>
      getKeysOrBuilderList();
  /**
   * <code>repeated .binary.AppStateSyncKey keys = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.AppStateSyncKeyOrBuilder getKeysOrBuilder(
      int index);
}
