// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface CallButtonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.CallButton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.HighlyStructuredMessage displayText = 1;</code>
   * @return Whether the displayText field is set.
   */
  boolean hasDisplayText();
  /**
   * <code>optional .binary.HighlyStructuredMessage displayText = 1;</code>
   * @return The displayText.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessage getDisplayText();
  /**
   * <code>optional .binary.HighlyStructuredMessage displayText = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessageOrBuilder getDisplayTextOrBuilder();

  /**
   * <code>optional .binary.HighlyStructuredMessage phoneNumber = 2;</code>
   * @return Whether the phoneNumber field is set.
   */
  boolean hasPhoneNumber();
  /**
   * <code>optional .binary.HighlyStructuredMessage phoneNumber = 2;</code>
   * @return The phoneNumber.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessage getPhoneNumber();
  /**
   * <code>optional .binary.HighlyStructuredMessage phoneNumber = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessageOrBuilder getPhoneNumberOrBuilder();
}
