// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface CancelPaymentRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.CancelPaymentRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   * @return The key.
   */
  com.xt.pfwhatsapp.ws.binary.protos.MessageKey getKey();
  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MessageKeyOrBuilder getKeyOrBuilder();
}
