// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface DeleteChatActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.DeleteChatAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.SyncActionMessageRange messageRange = 1;</code>
   * @return Whether the messageRange field is set.
   */
  boolean hasMessageRange();
  /**
   * <code>optional .binary.SyncActionMessageRange messageRange = 1;</code>
   * @return The messageRange.
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncActionMessageRange getMessageRange();
  /**
   * <code>optional .binary.SyncActionMessageRange messageRange = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncActionMessageRangeOrBuilder getMessageRangeOrBuilder();
}
