// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface FourRowTemplateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.FourRowTemplate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.HighlyStructuredMessage content = 6;</code>
   * @return Whether the content field is set.
   */
  boolean hasContent();
  /**
   * <code>optional .binary.HighlyStructuredMessage content = 6;</code>
   * @return The content.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessage getContent();
  /**
   * <code>optional .binary.HighlyStructuredMessage content = 6;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessageOrBuilder getContentOrBuilder();

  /**
   * <code>optional .binary.HighlyStructuredMessage footer = 7;</code>
   * @return Whether the footer field is set.
   */
  boolean hasFooter();
  /**
   * <code>optional .binary.HighlyStructuredMessage footer = 7;</code>
   * @return The footer.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessage getFooter();
  /**
   * <code>optional .binary.HighlyStructuredMessage footer = 7;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessageOrBuilder getFooterOrBuilder();

  /**
   * <code>repeated .binary.TemplateButton buttons = 8;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.TemplateButton>
      getButtonsList();
  /**
   * <code>repeated .binary.TemplateButton buttons = 8;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.TemplateButton getButtons(int index);
  /**
   * <code>repeated .binary.TemplateButton buttons = 8;</code>
   */
  int getButtonsCount();
  /**
   * <code>repeated .binary.TemplateButton buttons = 8;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.TemplateButtonOrBuilder>
      getButtonsOrBuilderList();
  /**
   * <code>repeated .binary.TemplateButton buttons = 8;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.TemplateButtonOrBuilder getButtonsOrBuilder(
      int index);

  /**
   * <code>.binary.DocumentMessage documentMessage = 1;</code>
   * @return Whether the documentMessage field is set.
   */
  boolean hasDocumentMessage();
  /**
   * <code>.binary.DocumentMessage documentMessage = 1;</code>
   * @return The documentMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.DocumentMessage getDocumentMessage();
  /**
   * <code>.binary.DocumentMessage documentMessage = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.DocumentMessageOrBuilder getDocumentMessageOrBuilder();

  /**
   * <code>.binary.HighlyStructuredMessage highlyStructuredMessage = 2;</code>
   * @return Whether the highlyStructuredMessage field is set.
   */
  boolean hasHighlyStructuredMessage();
  /**
   * <code>.binary.HighlyStructuredMessage highlyStructuredMessage = 2;</code>
   * @return The highlyStructuredMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessage getHighlyStructuredMessage();
  /**
   * <code>.binary.HighlyStructuredMessage highlyStructuredMessage = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessageOrBuilder getHighlyStructuredMessageOrBuilder();

  /**
   * <code>.binary.ImageMessage imageMessage = 3;</code>
   * @return Whether the imageMessage field is set.
   */
  boolean hasImageMessage();
  /**
   * <code>.binary.ImageMessage imageMessage = 3;</code>
   * @return The imageMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ImageMessage getImageMessage();
  /**
   * <code>.binary.ImageMessage imageMessage = 3;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ImageMessageOrBuilder getImageMessageOrBuilder();

  /**
   * <code>.binary.VideoMessage videoMessage = 4;</code>
   * @return Whether the videoMessage field is set.
   */
  boolean hasVideoMessage();
  /**
   * <code>.binary.VideoMessage videoMessage = 4;</code>
   * @return The videoMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.VideoMessage getVideoMessage();
  /**
   * <code>.binary.VideoMessage videoMessage = 4;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.VideoMessageOrBuilder getVideoMessageOrBuilder();

  /**
   * <code>.binary.LocationMessage locationMessage = 5;</code>
   * @return Whether the locationMessage field is set.
   */
  boolean hasLocationMessage();
  /**
   * <code>.binary.LocationMessage locationMessage = 5;</code>
   * @return The locationMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.LocationMessage getLocationMessage();
  /**
   * <code>.binary.LocationMessage locationMessage = 5;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.LocationMessageOrBuilder getLocationMessageOrBuilder();

  public com.xt.pfwhatsapp.ws.binary.protos.FourRowTemplate.TitleCase getTitleCase();
}
