// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface FutureProofMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.FutureProofMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.Message message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional .binary.Message message = 1;</code>
   * @return The message.
   */
  com.xt.pfwhatsapp.ws.binary.protos.Message getMessage();
  /**
   * <code>optional .binary.Message message = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MessageOrBuilder getMessageOrBuilder();
}
