// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface HandshakeMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.HandshakeMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.ClientHello clientHello = 2;</code>
   * @return Whether the clientHello field is set.
   */
  boolean hasClientHello();
  /**
   * <code>optional .binary.ClientHello clientHello = 2;</code>
   * @return The clientHello.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ClientHello getClientHello();
  /**
   * <code>optional .binary.ClientHello clientHello = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ClientHelloOrBuilder getClientHelloOrBuilder();

  /**
   * <code>optional .binary.ServerHello serverHello = 3;</code>
   * @return Whether the serverHello field is set.
   */
  boolean hasServerHello();
  /**
   * <code>optional .binary.ServerHello serverHello = 3;</code>
   * @return The serverHello.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ServerHello getServerHello();
  /**
   * <code>optional .binary.ServerHello serverHello = 3;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ServerHelloOrBuilder getServerHelloOrBuilder();

  /**
   * <code>optional .binary.ClientFinish clientFinish = 4;</code>
   * @return Whether the clientFinish field is set.
   */
  boolean hasClientFinish();
  /**
   * <code>optional .binary.ClientFinish clientFinish = 4;</code>
   * @return The clientFinish.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ClientFinish getClientFinish();
  /**
   * <code>optional .binary.ClientFinish clientFinish = 4;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ClientFinishOrBuilder getClientFinishOrBuilder();
}
