// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface HSMDateTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.HSMDateTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.binary.HSMDateTimeComponent component = 1;</code>
   * @return Whether the component field is set.
   */
  boolean hasComponent();
  /**
   * <code>.binary.HSMDateTimeComponent component = 1;</code>
   * @return The component.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HSMDateTimeComponent getComponent();
  /**
   * <code>.binary.HSMDateTimeComponent component = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HSMDateTimeComponentOrBuilder getComponentOrBuilder();

  /**
   * <code>.binary.HSMDateTimeUnixEpoch unixEpoch = 2;</code>
   * @return Whether the unixEpoch field is set.
   */
  boolean hasUnixEpoch();
  /**
   * <code>.binary.HSMDateTimeUnixEpoch unixEpoch = 2;</code>
   * @return The unixEpoch.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HSMDateTimeUnixEpoch getUnixEpoch();
  /**
   * <code>.binary.HSMDateTimeUnixEpoch unixEpoch = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HSMDateTimeUnixEpochOrBuilder getUnixEpochOrBuilder();

  public com.xt.pfwhatsapp.ws.binary.protos.HSMDateTime.DatetimeOneofCase getDatetimeOneofCase();
}
