// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string conversation = 1;</code>
   * @return Whether the conversation field is set.
   */
  boolean hasConversation();
  /**
   * <code>optional string conversation = 1;</code>
   * @return The conversation.
   */
  java.lang.String getConversation();
  /**
   * <code>optional string conversation = 1;</code>
   * @return The bytes for conversation.
   */
  com.google.protobuf.ByteString
      getConversationBytes();

  /**
   * <code>optional .binary.SenderKeyDistributionMessage senderKeyDistributionMessage = 2;</code>
   * @return Whether the senderKeyDistributionMessage field is set.
   */
  boolean hasSenderKeyDistributionMessage();
  /**
   * <code>optional .binary.SenderKeyDistributionMessage senderKeyDistributionMessage = 2;</code>
   * @return The senderKeyDistributionMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.SenderKeyDistributionMessage getSenderKeyDistributionMessage();
  /**
   * <code>optional .binary.SenderKeyDistributionMessage senderKeyDistributionMessage = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SenderKeyDistributionMessageOrBuilder getSenderKeyDistributionMessageOrBuilder();

  /**
   * <code>optional .binary.ImageMessage imageMessage = 3;</code>
   * @return Whether the imageMessage field is set.
   */
  boolean hasImageMessage();
  /**
   * <code>optional .binary.ImageMessage imageMessage = 3;</code>
   * @return The imageMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ImageMessage getImageMessage();
  /**
   * <code>optional .binary.ImageMessage imageMessage = 3;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ImageMessageOrBuilder getImageMessageOrBuilder();

  /**
   * <code>optional .binary.ContactMessage contactMessage = 4;</code>
   * @return Whether the contactMessage field is set.
   */
  boolean hasContactMessage();
  /**
   * <code>optional .binary.ContactMessage contactMessage = 4;</code>
   * @return The contactMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ContactMessage getContactMessage();
  /**
   * <code>optional .binary.ContactMessage contactMessage = 4;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ContactMessageOrBuilder getContactMessageOrBuilder();

  /**
   * <code>optional .binary.LocationMessage locationMessage = 5;</code>
   * @return Whether the locationMessage field is set.
   */
  boolean hasLocationMessage();
  /**
   * <code>optional .binary.LocationMessage locationMessage = 5;</code>
   * @return The locationMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.LocationMessage getLocationMessage();
  /**
   * <code>optional .binary.LocationMessage locationMessage = 5;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.LocationMessageOrBuilder getLocationMessageOrBuilder();

  /**
   * <code>optional .binary.ExtendedTextMessage extendedTextMessage = 6;</code>
   * @return Whether the extendedTextMessage field is set.
   */
  boolean hasExtendedTextMessage();
  /**
   * <code>optional .binary.ExtendedTextMessage extendedTextMessage = 6;</code>
   * @return The extendedTextMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ExtendedTextMessage getExtendedTextMessage();
  /**
   * <code>optional .binary.ExtendedTextMessage extendedTextMessage = 6;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ExtendedTextMessageOrBuilder getExtendedTextMessageOrBuilder();

  /**
   * <code>optional .binary.DocumentMessage documentMessage = 7;</code>
   * @return Whether the documentMessage field is set.
   */
  boolean hasDocumentMessage();
  /**
   * <code>optional .binary.DocumentMessage documentMessage = 7;</code>
   * @return The documentMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.DocumentMessage getDocumentMessage();
  /**
   * <code>optional .binary.DocumentMessage documentMessage = 7;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.DocumentMessageOrBuilder getDocumentMessageOrBuilder();

  /**
   * <code>optional .binary.AudioMessage audioMessage = 8;</code>
   * @return Whether the audioMessage field is set.
   */
  boolean hasAudioMessage();
  /**
   * <code>optional .binary.AudioMessage audioMessage = 8;</code>
   * @return The audioMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.AudioMessage getAudioMessage();
  /**
   * <code>optional .binary.AudioMessage audioMessage = 8;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.AudioMessageOrBuilder getAudioMessageOrBuilder();

  /**
   * <code>optional .binary.VideoMessage videoMessage = 9;</code>
   * @return Whether the videoMessage field is set.
   */
  boolean hasVideoMessage();
  /**
   * <code>optional .binary.VideoMessage videoMessage = 9;</code>
   * @return The videoMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.VideoMessage getVideoMessage();
  /**
   * <code>optional .binary.VideoMessage videoMessage = 9;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.VideoMessageOrBuilder getVideoMessageOrBuilder();

  /**
   * <code>optional .binary.Call call = 10;</code>
   * @return Whether the call field is set.
   */
  boolean hasCall();
  /**
   * <code>optional .binary.Call call = 10;</code>
   * @return The call.
   */
  com.xt.pfwhatsapp.ws.binary.protos.Call getCall();
  /**
   * <code>optional .binary.Call call = 10;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.CallOrBuilder getCallOrBuilder();

  /**
   * <code>optional .binary.Chat chat = 11;</code>
   * @return Whether the chat field is set.
   */
  boolean hasChat();
  /**
   * <code>optional .binary.Chat chat = 11;</code>
   * @return The chat.
   */
  com.xt.pfwhatsapp.ws.binary.protos.Chat getChat();
  /**
   * <code>optional .binary.Chat chat = 11;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ChatOrBuilder getChatOrBuilder();

  /**
   * <code>optional .binary.ProtocolMessage protocolMessage = 12;</code>
   * @return Whether the protocolMessage field is set.
   */
  boolean hasProtocolMessage();
  /**
   * <code>optional .binary.ProtocolMessage protocolMessage = 12;</code>
   * @return The protocolMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ProtocolMessage getProtocolMessage();
  /**
   * <code>optional .binary.ProtocolMessage protocolMessage = 12;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ProtocolMessageOrBuilder getProtocolMessageOrBuilder();

  /**
   * <code>optional .binary.ContactsArrayMessage contactsArrayMessage = 13;</code>
   * @return Whether the contactsArrayMessage field is set.
   */
  boolean hasContactsArrayMessage();
  /**
   * <code>optional .binary.ContactsArrayMessage contactsArrayMessage = 13;</code>
   * @return The contactsArrayMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ContactsArrayMessage getContactsArrayMessage();
  /**
   * <code>optional .binary.ContactsArrayMessage contactsArrayMessage = 13;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ContactsArrayMessageOrBuilder getContactsArrayMessageOrBuilder();

  /**
   * <code>optional .binary.HighlyStructuredMessage highlyStructuredMessage = 14;</code>
   * @return Whether the highlyStructuredMessage field is set.
   */
  boolean hasHighlyStructuredMessage();
  /**
   * <code>optional .binary.HighlyStructuredMessage highlyStructuredMessage = 14;</code>
   * @return The highlyStructuredMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessage getHighlyStructuredMessage();
  /**
   * <code>optional .binary.HighlyStructuredMessage highlyStructuredMessage = 14;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessageOrBuilder getHighlyStructuredMessageOrBuilder();

  /**
   * <code>optional .binary.SenderKeyDistributionMessage fastRatchetKeySenderKeyDistributionMessage = 15;</code>
   * @return Whether the fastRatchetKeySenderKeyDistributionMessage field is set.
   */
  boolean hasFastRatchetKeySenderKeyDistributionMessage();
  /**
   * <code>optional .binary.SenderKeyDistributionMessage fastRatchetKeySenderKeyDistributionMessage = 15;</code>
   * @return The fastRatchetKeySenderKeyDistributionMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.SenderKeyDistributionMessage getFastRatchetKeySenderKeyDistributionMessage();
  /**
   * <code>optional .binary.SenderKeyDistributionMessage fastRatchetKeySenderKeyDistributionMessage = 15;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SenderKeyDistributionMessageOrBuilder getFastRatchetKeySenderKeyDistributionMessageOrBuilder();

  /**
   * <code>optional .binary.SendPaymentMessage sendPaymentMessage = 16;</code>
   * @return Whether the sendPaymentMessage field is set.
   */
  boolean hasSendPaymentMessage();
  /**
   * <code>optional .binary.SendPaymentMessage sendPaymentMessage = 16;</code>
   * @return The sendPaymentMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.SendPaymentMessage getSendPaymentMessage();
  /**
   * <code>optional .binary.SendPaymentMessage sendPaymentMessage = 16;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SendPaymentMessageOrBuilder getSendPaymentMessageOrBuilder();

  /**
   * <code>optional .binary.LiveLocationMessage liveLocationMessage = 18;</code>
   * @return Whether the liveLocationMessage field is set.
   */
  boolean hasLiveLocationMessage();
  /**
   * <code>optional .binary.LiveLocationMessage liveLocationMessage = 18;</code>
   * @return The liveLocationMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.LiveLocationMessage getLiveLocationMessage();
  /**
   * <code>optional .binary.LiveLocationMessage liveLocationMessage = 18;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.LiveLocationMessageOrBuilder getLiveLocationMessageOrBuilder();

  /**
   * <code>optional .binary.RequestPaymentMessage requestPaymentMessage = 22;</code>
   * @return Whether the requestPaymentMessage field is set.
   */
  boolean hasRequestPaymentMessage();
  /**
   * <code>optional .binary.RequestPaymentMessage requestPaymentMessage = 22;</code>
   * @return The requestPaymentMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.RequestPaymentMessage getRequestPaymentMessage();
  /**
   * <code>optional .binary.RequestPaymentMessage requestPaymentMessage = 22;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.RequestPaymentMessageOrBuilder getRequestPaymentMessageOrBuilder();

  /**
   * <code>optional .binary.DeclinePaymentRequestMessage declinePaymentRequestMessage = 23;</code>
   * @return Whether the declinePaymentRequestMessage field is set.
   */
  boolean hasDeclinePaymentRequestMessage();
  /**
   * <code>optional .binary.DeclinePaymentRequestMessage declinePaymentRequestMessage = 23;</code>
   * @return The declinePaymentRequestMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.DeclinePaymentRequestMessage getDeclinePaymentRequestMessage();
  /**
   * <code>optional .binary.DeclinePaymentRequestMessage declinePaymentRequestMessage = 23;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.DeclinePaymentRequestMessageOrBuilder getDeclinePaymentRequestMessageOrBuilder();

  /**
   * <code>optional .binary.CancelPaymentRequestMessage cancelPaymentRequestMessage = 24;</code>
   * @return Whether the cancelPaymentRequestMessage field is set.
   */
  boolean hasCancelPaymentRequestMessage();
  /**
   * <code>optional .binary.CancelPaymentRequestMessage cancelPaymentRequestMessage = 24;</code>
   * @return The cancelPaymentRequestMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.CancelPaymentRequestMessage getCancelPaymentRequestMessage();
  /**
   * <code>optional .binary.CancelPaymentRequestMessage cancelPaymentRequestMessage = 24;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.CancelPaymentRequestMessageOrBuilder getCancelPaymentRequestMessageOrBuilder();

  /**
   * <code>optional .binary.TemplateMessage templateMessage = 25;</code>
   * @return Whether the templateMessage field is set.
   */
  boolean hasTemplateMessage();
  /**
   * <code>optional .binary.TemplateMessage templateMessage = 25;</code>
   * @return The templateMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.TemplateMessage getTemplateMessage();
  /**
   * <code>optional .binary.TemplateMessage templateMessage = 25;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.TemplateMessageOrBuilder getTemplateMessageOrBuilder();

  /**
   * <code>optional .binary.StickerMessage stickerMessage = 26;</code>
   * @return Whether the stickerMessage field is set.
   */
  boolean hasStickerMessage();
  /**
   * <code>optional .binary.StickerMessage stickerMessage = 26;</code>
   * @return The stickerMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.StickerMessage getStickerMessage();
  /**
   * <code>optional .binary.StickerMessage stickerMessage = 26;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.StickerMessageOrBuilder getStickerMessageOrBuilder();

  /**
   * <code>optional .binary.GroupInviteMessage groupInviteMessage = 28;</code>
   * @return Whether the groupInviteMessage field is set.
   */
  boolean hasGroupInviteMessage();
  /**
   * <code>optional .binary.GroupInviteMessage groupInviteMessage = 28;</code>
   * @return The groupInviteMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.GroupInviteMessage getGroupInviteMessage();
  /**
   * <code>optional .binary.GroupInviteMessage groupInviteMessage = 28;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.GroupInviteMessageOrBuilder getGroupInviteMessageOrBuilder();

  /**
   * <code>optional .binary.TemplateButtonReplyMessage templateButtonReplyMessage = 29;</code>
   * @return Whether the templateButtonReplyMessage field is set.
   */
  boolean hasTemplateButtonReplyMessage();
  /**
   * <code>optional .binary.TemplateButtonReplyMessage templateButtonReplyMessage = 29;</code>
   * @return The templateButtonReplyMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.TemplateButtonReplyMessage getTemplateButtonReplyMessage();
  /**
   * <code>optional .binary.TemplateButtonReplyMessage templateButtonReplyMessage = 29;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.TemplateButtonReplyMessageOrBuilder getTemplateButtonReplyMessageOrBuilder();

  /**
   * <code>optional .binary.ProductMessage productMessage = 30;</code>
   * @return Whether the productMessage field is set.
   */
  boolean hasProductMessage();
  /**
   * <code>optional .binary.ProductMessage productMessage = 30;</code>
   * @return The productMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ProductMessage getProductMessage();
  /**
   * <code>optional .binary.ProductMessage productMessage = 30;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ProductMessageOrBuilder getProductMessageOrBuilder();

  /**
   * <code>optional .binary.DeviceSentMessage deviceSentMessage = 31;</code>
   * @return Whether the deviceSentMessage field is set.
   */
  boolean hasDeviceSentMessage();
  /**
   * <code>optional .binary.DeviceSentMessage deviceSentMessage = 31;</code>
   * @return The deviceSentMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.DeviceSentMessage getDeviceSentMessage();
  /**
   * <code>optional .binary.DeviceSentMessage deviceSentMessage = 31;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.DeviceSentMessageOrBuilder getDeviceSentMessageOrBuilder();

  /**
   * <code>optional .binary.MessageContextInfo messageContextInfo = 35;</code>
   * @return Whether the messageContextInfo field is set.
   */
  boolean hasMessageContextInfo();
  /**
   * <code>optional .binary.MessageContextInfo messageContextInfo = 35;</code>
   * @return The messageContextInfo.
   */
  com.xt.pfwhatsapp.ws.binary.protos.MessageContextInfo getMessageContextInfo();
  /**
   * <code>optional .binary.MessageContextInfo messageContextInfo = 35;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MessageContextInfoOrBuilder getMessageContextInfoOrBuilder();

  /**
   * <code>optional .binary.ListMessage listMessage = 36;</code>
   * @return Whether the listMessage field is set.
   */
  boolean hasListMessage();
  /**
   * <code>optional .binary.ListMessage listMessage = 36;</code>
   * @return The listMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ListMessage getListMessage();
  /**
   * <code>optional .binary.ListMessage listMessage = 36;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ListMessageOrBuilder getListMessageOrBuilder();

  /**
   * <code>optional .binary.FutureProofMessage viewOnceMessage = 37;</code>
   * @return Whether the viewOnceMessage field is set.
   */
  boolean hasViewOnceMessage();
  /**
   * <code>optional .binary.FutureProofMessage viewOnceMessage = 37;</code>
   * @return The viewOnceMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.FutureProofMessage getViewOnceMessage();
  /**
   * <code>optional .binary.FutureProofMessage viewOnceMessage = 37;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.FutureProofMessageOrBuilder getViewOnceMessageOrBuilder();

  /**
   * <code>optional .binary.OrderMessage orderMessage = 38;</code>
   * @return Whether the orderMessage field is set.
   */
  boolean hasOrderMessage();
  /**
   * <code>optional .binary.OrderMessage orderMessage = 38;</code>
   * @return The orderMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.OrderMessage getOrderMessage();
  /**
   * <code>optional .binary.OrderMessage orderMessage = 38;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.OrderMessageOrBuilder getOrderMessageOrBuilder();

  /**
   * <code>optional .binary.ListResponseMessage listResponseMessage = 39;</code>
   * @return Whether the listResponseMessage field is set.
   */
  boolean hasListResponseMessage();
  /**
   * <code>optional .binary.ListResponseMessage listResponseMessage = 39;</code>
   * @return The listResponseMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ListResponseMessage getListResponseMessage();
  /**
   * <code>optional .binary.ListResponseMessage listResponseMessage = 39;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ListResponseMessageOrBuilder getListResponseMessageOrBuilder();

  /**
   * <code>optional .binary.FutureProofMessage ephemeralMessage = 40;</code>
   * @return Whether the ephemeralMessage field is set.
   */
  boolean hasEphemeralMessage();
  /**
   * <code>optional .binary.FutureProofMessage ephemeralMessage = 40;</code>
   * @return The ephemeralMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.FutureProofMessage getEphemeralMessage();
  /**
   * <code>optional .binary.FutureProofMessage ephemeralMessage = 40;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.FutureProofMessageOrBuilder getEphemeralMessageOrBuilder();

  /**
   * <code>optional .binary.InvoiceMessage invoiceMessage = 41;</code>
   * @return Whether the invoiceMessage field is set.
   */
  boolean hasInvoiceMessage();
  /**
   * <code>optional .binary.InvoiceMessage invoiceMessage = 41;</code>
   * @return The invoiceMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.InvoiceMessage getInvoiceMessage();
  /**
   * <code>optional .binary.InvoiceMessage invoiceMessage = 41;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.InvoiceMessageOrBuilder getInvoiceMessageOrBuilder();

  /**
   * <code>optional .binary.ButtonsMessage buttonsMessage = 42;</code>
   * @return Whether the buttonsMessage field is set.
   */
  boolean hasButtonsMessage();
  /**
   * <code>optional .binary.ButtonsMessage buttonsMessage = 42;</code>
   * @return The buttonsMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ButtonsMessage getButtonsMessage();
  /**
   * <code>optional .binary.ButtonsMessage buttonsMessage = 42;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ButtonsMessageOrBuilder getButtonsMessageOrBuilder();

  /**
   * <code>optional .binary.ButtonsResponseMessage buttonsResponseMessage = 43;</code>
   * @return Whether the buttonsResponseMessage field is set.
   */
  boolean hasButtonsResponseMessage();
  /**
   * <code>optional .binary.ButtonsResponseMessage buttonsResponseMessage = 43;</code>
   * @return The buttonsResponseMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ButtonsResponseMessage getButtonsResponseMessage();
  /**
   * <code>optional .binary.ButtonsResponseMessage buttonsResponseMessage = 43;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ButtonsResponseMessageOrBuilder getButtonsResponseMessageOrBuilder();

  /**
   * <code>optional .binary.PaymentInviteMessage paymentInviteMessage = 44;</code>
   * @return Whether the paymentInviteMessage field is set.
   */
  boolean hasPaymentInviteMessage();
  /**
   * <code>optional .binary.PaymentInviteMessage paymentInviteMessage = 44;</code>
   * @return The paymentInviteMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.PaymentInviteMessage getPaymentInviteMessage();
  /**
   * <code>optional .binary.PaymentInviteMessage paymentInviteMessage = 44;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.PaymentInviteMessageOrBuilder getPaymentInviteMessageOrBuilder();
}
