// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface MsgRowOpaqueDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.MsgRowOpaqueData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.MsgOpaqueData currentMsg = 1;</code>
   * @return Whether the currentMsg field is set.
   */
  boolean hasCurrentMsg();
  /**
   * <code>optional .binary.MsgOpaqueData currentMsg = 1;</code>
   * @return The currentMsg.
   */
  com.xt.pfwhatsapp.ws.binary.protos.MsgOpaqueData getCurrentMsg();
  /**
   * <code>optional .binary.MsgOpaqueData currentMsg = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MsgOpaqueDataOrBuilder getCurrentMsgOrBuilder();

  /**
   * <code>optional .binary.MsgOpaqueData quotedMsg = 2;</code>
   * @return Whether the quotedMsg field is set.
   */
  boolean hasQuotedMsg();
  /**
   * <code>optional .binary.MsgOpaqueData quotedMsg = 2;</code>
   * @return The quotedMsg.
   */
  com.xt.pfwhatsapp.ws.binary.protos.MsgOpaqueData getQuotedMsg();
  /**
   * <code>optional .binary.MsgOpaqueData quotedMsg = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MsgOpaqueDataOrBuilder getQuotedMsgOrBuilder();
}
