// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface ProductSectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.ProductSection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string title = 1;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>optional string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>repeated .binary.Product products = 2;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.Product>
      getProductsList();
  /**
   * <code>repeated .binary.Product products = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.Product getProducts(int index);
  /**
   * <code>repeated .binary.Product products = 2;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .binary.Product products = 2;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.ProductOrBuilder>
      getProductsOrBuilderList();
  /**
   * <code>repeated .binary.Product products = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ProductOrBuilder getProductsOrBuilder(
      int index);
}
