// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface QuickReplyButtonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.QuickReplyButton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.HighlyStructuredMessage displayText = 1;</code>
   * @return Whether the displayText field is set.
   */
  boolean hasDisplayText();
  /**
   * <code>optional .binary.HighlyStructuredMessage displayText = 1;</code>
   * @return The displayText.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessage getDisplayText();
  /**
   * <code>optional .binary.HighlyStructuredMessage displayText = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessageOrBuilder getDisplayTextOrBuilder();

  /**
   * <code>optional string id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
