// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface RecentEmojiWeightsActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.RecentEmojiWeightsAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .binary.RecentEmojiWeight weights = 1;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.RecentEmojiWeight>
      getWeightsList();
  /**
   * <code>repeated .binary.RecentEmojiWeight weights = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentEmojiWeight getWeights(int index);
  /**
   * <code>repeated .binary.RecentEmojiWeight weights = 1;</code>
   */
  int getWeightsCount();
  /**
   * <code>repeated .binary.RecentEmojiWeight weights = 1;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.RecentEmojiWeightOrBuilder>
      getWeightsOrBuilderList();
  /**
   * <code>repeated .binary.RecentEmojiWeight weights = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentEmojiWeightOrBuilder getWeightsOrBuilder(
      int index);
}
