// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface RecentStickerWeightsActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.RecentStickerWeightsAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .binary.RecentStickerWeight weights = 1;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.RecentStickerWeight>
      getWeightsList();
  /**
   * <code>repeated .binary.RecentStickerWeight weights = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentStickerWeight getWeights(int index);
  /**
   * <code>repeated .binary.RecentStickerWeight weights = 1;</code>
   */
  int getWeightsCount();
  /**
   * <code>repeated .binary.RecentStickerWeight weights = 1;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.RecentStickerWeightOrBuilder>
      getWeightsOrBuilderList();
  /**
   * <code>repeated .binary.RecentStickerWeight weights = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentStickerWeightOrBuilder getWeightsOrBuilder(
      int index);
}
