// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface RequestPaymentMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.RequestPaymentMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.Message noteMessage = 4;</code>
   * @return Whether the noteMessage field is set.
   */
  boolean hasNoteMessage();
  /**
   * <code>optional .binary.Message noteMessage = 4;</code>
   * @return The noteMessage.
   */
  com.xt.pfwhatsapp.ws.binary.protos.Message getNoteMessage();
  /**
   * <code>optional .binary.Message noteMessage = 4;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MessageOrBuilder getNoteMessageOrBuilder();

  /**
   * <code>optional string currencyCodeIso4217 = 1;</code>
   * @return Whether the currencyCodeIso4217 field is set.
   */
  boolean hasCurrencyCodeIso4217();
  /**
   * <code>optional string currencyCodeIso4217 = 1;</code>
   * @return The currencyCodeIso4217.
   */
  java.lang.String getCurrencyCodeIso4217();
  /**
   * <code>optional string currencyCodeIso4217 = 1;</code>
   * @return The bytes for currencyCodeIso4217.
   */
  com.google.protobuf.ByteString
      getCurrencyCodeIso4217Bytes();

  /**
   * <code>optional uint64 amount1000 = 2;</code>
   * @return Whether the amount1000 field is set.
   */
  boolean hasAmount1000();
  /**
   * <code>optional uint64 amount1000 = 2;</code>
   * @return The amount1000.
   */
  long getAmount1000();

  /**
   * <code>optional string requestFrom = 3;</code>
   * @return Whether the requestFrom field is set.
   */
  boolean hasRequestFrom();
  /**
   * <code>optional string requestFrom = 3;</code>
   * @return The requestFrom.
   */
  java.lang.String getRequestFrom();
  /**
   * <code>optional string requestFrom = 3;</code>
   * @return The bytes for requestFrom.
   */
  com.google.protobuf.ByteString
      getRequestFromBytes();

  /**
   * <code>optional int64 expiryTimestamp = 5;</code>
   * @return Whether the expiryTimestamp field is set.
   */
  boolean hasExpiryTimestamp();
  /**
   * <code>optional int64 expiryTimestamp = 5;</code>
   * @return The expiryTimestamp.
   */
  long getExpiryTimestamp();

  /**
   * <code>optional .binary.Money amount = 6;</code>
   * @return Whether the amount field is set.
   */
  boolean hasAmount();
  /**
   * <code>optional .binary.Money amount = 6;</code>
   * @return The amount.
   */
  com.xt.pfwhatsapp.ws.binary.protos.Money getAmount();
  /**
   * <code>optional .binary.Money amount = 6;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MoneyOrBuilder getAmountOrBuilder();

  /**
   * <code>optional .binary.PaymentBackground background = 7;</code>
   * @return Whether the background field is set.
   */
  boolean hasBackground();
  /**
   * <code>optional .binary.PaymentBackground background = 7;</code>
   * @return The background.
   */
  com.xt.pfwhatsapp.ws.binary.protos.PaymentBackground getBackground();
  /**
   * <code>optional .binary.PaymentBackground background = 7;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.PaymentBackgroundOrBuilder getBackgroundOrBuilder();
}
