// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface SectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.Section)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string title = 1;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>optional string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>repeated .binary.Row rows = 2;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.Row>
      getRowsList();
  /**
   * <code>repeated .binary.Row rows = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.Row getRows(int index);
  /**
   * <code>repeated .binary.Row rows = 2;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .binary.Row rows = 2;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.RowOrBuilder>
      getRowsOrBuilderList();
  /**
   * <code>repeated .binary.Row rows = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.RowOrBuilder getRowsOrBuilder(
      int index);
}
