// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface SyncdSnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.SyncdSnapshot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.SyncdVersion version = 1;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>optional .binary.SyncdVersion version = 1;</code>
   * @return The version.
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdVersion getVersion();
  /**
   * <code>optional .binary.SyncdVersion version = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdVersionOrBuilder getVersionOrBuilder();

  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.SyncdRecord>
      getRecordsList();
  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdRecord getRecords(int index);
  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.SyncdRecordOrBuilder>
      getRecordsOrBuilderList();
  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdRecordOrBuilder getRecordsOrBuilder(
      int index);

  /**
   * <code>optional bytes mac = 3;</code>
   * @return Whether the mac field is set.
   */
  boolean hasMac();
  /**
   * <code>optional bytes mac = 3;</code>
   * @return The mac.
   */
  com.google.protobuf.ByteString getMac();

  /**
   * <code>optional .binary.KeyId keyId = 4;</code>
   * @return Whether the keyId field is set.
   */
  boolean hasKeyId();
  /**
   * <code>optional .binary.KeyId keyId = 4;</code>
   * @return The keyId.
   */
  com.xt.pfwhatsapp.ws.binary.protos.KeyId getKeyId();
  /**
   * <code>optional .binary.KeyId keyId = 4;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.KeyIdOrBuilder getKeyIdOrBuilder();
}
