// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface SyncActionMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.SyncActionMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   * @return The key.
   */
  com.xt.pfwhatsapp.ws.binary.protos.MessageKey getKey();
  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MessageKeyOrBuilder getKeyOrBuilder();

  /**
   * <code>optional int64 timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>optional int64 timestamp = 2;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
