// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface SyncActionValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.SyncActionValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 timestamp = 1;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>optional int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>optional .binary.StarAction starAction = 2;</code>
   * @return Whether the starAction field is set.
   */
  boolean hasStarAction();
  /**
   * <code>optional .binary.StarAction starAction = 2;</code>
   * @return The starAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.StarAction getStarAction();
  /**
   * <code>optional .binary.StarAction starAction = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.StarActionOrBuilder getStarActionOrBuilder();

  /**
   * <code>optional .binary.ContactAction contactAction = 3;</code>
   * @return Whether the contactAction field is set.
   */
  boolean hasContactAction();
  /**
   * <code>optional .binary.ContactAction contactAction = 3;</code>
   * @return The contactAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ContactAction getContactAction();
  /**
   * <code>optional .binary.ContactAction contactAction = 3;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ContactActionOrBuilder getContactActionOrBuilder();

  /**
   * <code>optional .binary.MuteAction muteAction = 4;</code>
   * @return Whether the muteAction field is set.
   */
  boolean hasMuteAction();
  /**
   * <code>optional .binary.MuteAction muteAction = 4;</code>
   * @return The muteAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.MuteAction getMuteAction();
  /**
   * <code>optional .binary.MuteAction muteAction = 4;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MuteActionOrBuilder getMuteActionOrBuilder();

  /**
   * <code>optional .binary.PinAction pinAction = 5;</code>
   * @return Whether the pinAction field is set.
   */
  boolean hasPinAction();
  /**
   * <code>optional .binary.PinAction pinAction = 5;</code>
   * @return The pinAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.PinAction getPinAction();
  /**
   * <code>optional .binary.PinAction pinAction = 5;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.PinActionOrBuilder getPinActionOrBuilder();

  /**
   * <code>optional .binary.SecurityNotificationSetting securityNotificationSetting = 6;</code>
   * @return Whether the securityNotificationSetting field is set.
   */
  boolean hasSecurityNotificationSetting();
  /**
   * <code>optional .binary.SecurityNotificationSetting securityNotificationSetting = 6;</code>
   * @return The securityNotificationSetting.
   */
  com.xt.pfwhatsapp.ws.binary.protos.SecurityNotificationSetting getSecurityNotificationSetting();
  /**
   * <code>optional .binary.SecurityNotificationSetting securityNotificationSetting = 6;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SecurityNotificationSettingOrBuilder getSecurityNotificationSettingOrBuilder();

  /**
   * <code>optional .binary.PushNameSetting pushNameSetting = 7;</code>
   * @return Whether the pushNameSetting field is set.
   */
  boolean hasPushNameSetting();
  /**
   * <code>optional .binary.PushNameSetting pushNameSetting = 7;</code>
   * @return The pushNameSetting.
   */
  com.xt.pfwhatsapp.ws.binary.protos.PushNameSetting getPushNameSetting();
  /**
   * <code>optional .binary.PushNameSetting pushNameSetting = 7;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.PushNameSettingOrBuilder getPushNameSettingOrBuilder();

  /**
   * <code>optional .binary.QuickReplyAction quickReplyAction = 8;</code>
   * @return Whether the quickReplyAction field is set.
   */
  boolean hasQuickReplyAction();
  /**
   * <code>optional .binary.QuickReplyAction quickReplyAction = 8;</code>
   * @return The quickReplyAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.QuickReplyAction getQuickReplyAction();
  /**
   * <code>optional .binary.QuickReplyAction quickReplyAction = 8;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.QuickReplyActionOrBuilder getQuickReplyActionOrBuilder();

  /**
   * <code>optional .binary.RecentStickerWeightsAction recentStickerWeightsAction = 9;</code>
   * @return Whether the recentStickerWeightsAction field is set.
   */
  boolean hasRecentStickerWeightsAction();
  /**
   * <code>optional .binary.RecentStickerWeightsAction recentStickerWeightsAction = 9;</code>
   * @return The recentStickerWeightsAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentStickerWeightsAction getRecentStickerWeightsAction();
  /**
   * <code>optional .binary.RecentStickerWeightsAction recentStickerWeightsAction = 9;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentStickerWeightsActionOrBuilder getRecentStickerWeightsActionOrBuilder();

  /**
   * <code>optional .binary.RecentStickerMetadata recentStickerMetadata = 10;</code>
   * @return Whether the recentStickerMetadata field is set.
   */
  boolean hasRecentStickerMetadata();
  /**
   * <code>optional .binary.RecentStickerMetadata recentStickerMetadata = 10;</code>
   * @return The recentStickerMetadata.
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentStickerMetadata getRecentStickerMetadata();
  /**
   * <code>optional .binary.RecentStickerMetadata recentStickerMetadata = 10;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentStickerMetadataOrBuilder getRecentStickerMetadataOrBuilder();

  /**
   * <code>optional .binary.RecentEmojiWeightsAction recentEmojiWeightsAction = 11;</code>
   * @return Whether the recentEmojiWeightsAction field is set.
   */
  boolean hasRecentEmojiWeightsAction();
  /**
   * <code>optional .binary.RecentEmojiWeightsAction recentEmojiWeightsAction = 11;</code>
   * @return The recentEmojiWeightsAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentEmojiWeightsAction getRecentEmojiWeightsAction();
  /**
   * <code>optional .binary.RecentEmojiWeightsAction recentEmojiWeightsAction = 11;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.RecentEmojiWeightsActionOrBuilder getRecentEmojiWeightsActionOrBuilder();

  /**
   * <code>optional .binary.LabelEditAction labelEditAction = 14;</code>
   * @return Whether the labelEditAction field is set.
   */
  boolean hasLabelEditAction();
  /**
   * <code>optional .binary.LabelEditAction labelEditAction = 14;</code>
   * @return The labelEditAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.LabelEditAction getLabelEditAction();
  /**
   * <code>optional .binary.LabelEditAction labelEditAction = 14;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.LabelEditActionOrBuilder getLabelEditActionOrBuilder();

  /**
   * <code>optional .binary.LabelAssociationAction labelAssociationAction = 15;</code>
   * @return Whether the labelAssociationAction field is set.
   */
  boolean hasLabelAssociationAction();
  /**
   * <code>optional .binary.LabelAssociationAction labelAssociationAction = 15;</code>
   * @return The labelAssociationAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.LabelAssociationAction getLabelAssociationAction();
  /**
   * <code>optional .binary.LabelAssociationAction labelAssociationAction = 15;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.LabelAssociationActionOrBuilder getLabelAssociationActionOrBuilder();

  /**
   * <code>optional .binary.LocaleSetting localeSetting = 16;</code>
   * @return Whether the localeSetting field is set.
   */
  boolean hasLocaleSetting();
  /**
   * <code>optional .binary.LocaleSetting localeSetting = 16;</code>
   * @return The localeSetting.
   */
  com.xt.pfwhatsapp.ws.binary.protos.LocaleSetting getLocaleSetting();
  /**
   * <code>optional .binary.LocaleSetting localeSetting = 16;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.LocaleSettingOrBuilder getLocaleSettingOrBuilder();

  /**
   * <code>optional .binary.ArchiveChatAction archiveChatAction = 17;</code>
   * @return Whether the archiveChatAction field is set.
   */
  boolean hasArchiveChatAction();
  /**
   * <code>optional .binary.ArchiveChatAction archiveChatAction = 17;</code>
   * @return The archiveChatAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ArchiveChatAction getArchiveChatAction();
  /**
   * <code>optional .binary.ArchiveChatAction archiveChatAction = 17;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ArchiveChatActionOrBuilder getArchiveChatActionOrBuilder();

  /**
   * <code>optional .binary.DeleteMessageForMeAction deleteMessageForMeAction = 18;</code>
   * @return Whether the deleteMessageForMeAction field is set.
   */
  boolean hasDeleteMessageForMeAction();
  /**
   * <code>optional .binary.DeleteMessageForMeAction deleteMessageForMeAction = 18;</code>
   * @return The deleteMessageForMeAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.DeleteMessageForMeAction getDeleteMessageForMeAction();
  /**
   * <code>optional .binary.DeleteMessageForMeAction deleteMessageForMeAction = 18;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.DeleteMessageForMeActionOrBuilder getDeleteMessageForMeActionOrBuilder();

  /**
   * <code>optional .binary.KeyExpiration keyExpiration = 19;</code>
   * @return Whether the keyExpiration field is set.
   */
  boolean hasKeyExpiration();
  /**
   * <code>optional .binary.KeyExpiration keyExpiration = 19;</code>
   * @return The keyExpiration.
   */
  com.xt.pfwhatsapp.ws.binary.protos.KeyExpiration getKeyExpiration();
  /**
   * <code>optional .binary.KeyExpiration keyExpiration = 19;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.KeyExpirationOrBuilder getKeyExpirationOrBuilder();

  /**
   * <code>optional .binary.MarkChatAsReadAction markChatAsReadAction = 20;</code>
   * @return Whether the markChatAsReadAction field is set.
   */
  boolean hasMarkChatAsReadAction();
  /**
   * <code>optional .binary.MarkChatAsReadAction markChatAsReadAction = 20;</code>
   * @return The markChatAsReadAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.MarkChatAsReadAction getMarkChatAsReadAction();
  /**
   * <code>optional .binary.MarkChatAsReadAction markChatAsReadAction = 20;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.MarkChatAsReadActionOrBuilder getMarkChatAsReadActionOrBuilder();

  /**
   * <code>optional .binary.ClearChatAction clearChatAction = 21;</code>
   * @return Whether the clearChatAction field is set.
   */
  boolean hasClearChatAction();
  /**
   * <code>optional .binary.ClearChatAction clearChatAction = 21;</code>
   * @return The clearChatAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ClearChatAction getClearChatAction();
  /**
   * <code>optional .binary.ClearChatAction clearChatAction = 21;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ClearChatActionOrBuilder getClearChatActionOrBuilder();

  /**
   * <code>optional .binary.DeleteChatAction deleteChatAction = 22;</code>
   * @return Whether the deleteChatAction field is set.
   */
  boolean hasDeleteChatAction();
  /**
   * <code>optional .binary.DeleteChatAction deleteChatAction = 22;</code>
   * @return The deleteChatAction.
   */
  com.xt.pfwhatsapp.ws.binary.protos.DeleteChatAction getDeleteChatAction();
  /**
   * <code>optional .binary.DeleteChatAction deleteChatAction = 22;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.DeleteChatActionOrBuilder getDeleteChatActionOrBuilder();

  /**
   * <code>optional .binary.UnarchiveChatsSetting unarchiveChatsSetting = 23;</code>
   * @return Whether the unarchiveChatsSetting field is set.
   */
  boolean hasUnarchiveChatsSetting();
  /**
   * <code>optional .binary.UnarchiveChatsSetting unarchiveChatsSetting = 23;</code>
   * @return The unarchiveChatsSetting.
   */
  com.xt.pfwhatsapp.ws.binary.protos.UnarchiveChatsSetting getUnarchiveChatsSetting();
  /**
   * <code>optional .binary.UnarchiveChatsSetting unarchiveChatsSetting = 23;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.UnarchiveChatsSettingOrBuilder getUnarchiveChatsSettingOrBuilder();
}
