// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface SyncdMutationsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.SyncdMutations)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .binary.SyncdMutation mutations = 1;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.SyncdMutation>
      getMutationsList();
  /**
   * <code>repeated .binary.SyncdMutation mutations = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdMutation getMutations(int index);
  /**
   * <code>repeated .binary.SyncdMutation mutations = 1;</code>
   */
  int getMutationsCount();
  /**
   * <code>repeated .binary.SyncdMutation mutations = 1;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.SyncdMutationOrBuilder>
      getMutationsOrBuilderList();
  /**
   * <code>repeated .binary.SyncdMutation mutations = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdMutationOrBuilder getMutationsOrBuilder(
      int index);
}
