// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface SyncActionMessageRangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.SyncActionMessageRange)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 lastMessageTimestamp = 1;</code>
   * @return Whether the lastMessageTimestamp field is set.
   */
  boolean hasLastMessageTimestamp();
  /**
   * <code>optional int64 lastMessageTimestamp = 1;</code>
   * @return The lastMessageTimestamp.
   */
  long getLastMessageTimestamp();

  /**
   * <code>optional int64 lastSystemMessageTimestamp = 2;</code>
   * @return Whether the lastSystemMessageTimestamp field is set.
   */
  boolean hasLastSystemMessageTimestamp();
  /**
   * <code>optional int64 lastSystemMessageTimestamp = 2;</code>
   * @return The lastSystemMessageTimestamp.
   */
  long getLastSystemMessageTimestamp();

  /**
   * <code>repeated .binary.SyncActionMessage messages = 3;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.SyncActionMessage>
      getMessagesList();
  /**
   * <code>repeated .binary.SyncActionMessage messages = 3;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncActionMessage getMessages(int index);
  /**
   * <code>repeated .binary.SyncActionMessage messages = 3;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .binary.SyncActionMessage messages = 3;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.SyncActionMessageOrBuilder>
      getMessagesOrBuilderList();
  /**
   * <code>repeated .binary.SyncActionMessage messages = 3;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncActionMessageOrBuilder getMessagesOrBuilder(
      int index);
}
