// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface SyncdPatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.SyncdPatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.SyncdVersion version = 1;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>optional .binary.SyncdVersion version = 1;</code>
   * @return The version.
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdVersion getVersion();
  /**
   * <code>optional .binary.SyncdVersion version = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdVersionOrBuilder getVersionOrBuilder();

  /**
   * <code>repeated .binary.SyncdMutation mutations = 2;</code>
   */
  java.util.List<com.xt.pfwhatsapp.ws.binary.protos.SyncdMutation>
      getMutationsList();
  /**
   * <code>repeated .binary.SyncdMutation mutations = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdMutation getMutations(int index);
  /**
   * <code>repeated .binary.SyncdMutation mutations = 2;</code>
   */
  int getMutationsCount();
  /**
   * <code>repeated .binary.SyncdMutation mutations = 2;</code>
   */
  java.util.List<? extends com.xt.pfwhatsapp.ws.binary.protos.SyncdMutationOrBuilder>
      getMutationsOrBuilderList();
  /**
   * <code>repeated .binary.SyncdMutation mutations = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdMutationOrBuilder getMutationsOrBuilder(
      int index);

  /**
   * <code>optional .binary.ExternalBlobReference externalMutations = 3;</code>
   * @return Whether the externalMutations field is set.
   */
  boolean hasExternalMutations();
  /**
   * <code>optional .binary.ExternalBlobReference externalMutations = 3;</code>
   * @return The externalMutations.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ExternalBlobReference getExternalMutations();
  /**
   * <code>optional .binary.ExternalBlobReference externalMutations = 3;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ExternalBlobReferenceOrBuilder getExternalMutationsOrBuilder();

  /**
   * <code>optional bytes snapshotMac = 4;</code>
   * @return Whether the snapshotMac field is set.
   */
  boolean hasSnapshotMac();
  /**
   * <code>optional bytes snapshotMac = 4;</code>
   * @return The snapshotMac.
   */
  com.google.protobuf.ByteString getSnapshotMac();

  /**
   * <code>optional bytes patchMac = 5;</code>
   * @return Whether the patchMac field is set.
   */
  boolean hasPatchMac();
  /**
   * <code>optional bytes patchMac = 5;</code>
   * @return The patchMac.
   */
  com.google.protobuf.ByteString getPatchMac();

  /**
   * <code>optional .binary.KeyId keyId = 6;</code>
   * @return Whether the keyId field is set.
   */
  boolean hasKeyId();
  /**
   * <code>optional .binary.KeyId keyId = 6;</code>
   * @return The keyId.
   */
  com.xt.pfwhatsapp.ws.binary.protos.KeyId getKeyId();
  /**
   * <code>optional .binary.KeyId keyId = 6;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.KeyIdOrBuilder getKeyIdOrBuilder();

  /**
   * <code>optional .binary.ExitCode exitCode = 7;</code>
   * @return Whether the exitCode field is set.
   */
  boolean hasExitCode();
  /**
   * <code>optional .binary.ExitCode exitCode = 7;</code>
   * @return The exitCode.
   */
  com.xt.pfwhatsapp.ws.binary.protos.ExitCode getExitCode();
  /**
   * <code>optional .binary.ExitCode exitCode = 7;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.ExitCodeOrBuilder getExitCodeOrBuilder();

  /**
   * <code>optional uint32 deviceIndex = 8;</code>
   * @return Whether the deviceIndex field is set.
   */
  boolean hasDeviceIndex();
  /**
   * <code>optional uint32 deviceIndex = 8;</code>
   * @return The deviceIndex.
   */
  int getDeviceIndex();
}
