// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface SyncdMutationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.SyncdMutation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.SyncdMutation.SyncdMutationSyncdOperation operation = 1;</code>
   * @return Whether the operation field is set.
   */
  boolean hasOperation();
  /**
   * <code>optional .binary.SyncdMutation.SyncdMutationSyncdOperation operation = 1;</code>
   * @return The operation.
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdMutation.SyncdMutationSyncdOperation getOperation();

  /**
   * <code>optional .binary.SyncdRecord record = 2;</code>
   * @return Whether the record field is set.
   */
  boolean hasRecord();
  /**
   * <code>optional .binary.SyncdRecord record = 2;</code>
   * @return The record.
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdRecord getRecord();
  /**
   * <code>optional .binary.SyncdRecord record = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.SyncdRecordOrBuilder getRecordOrBuilder();
}
