// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package com.xt.pfwhatsapp.ws.binary.protos;

public interface URLButtonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.URLButton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.HighlyStructuredMessage displayText = 1;</code>
   * @return Whether the displayText field is set.
   */
  boolean hasDisplayText();
  /**
   * <code>optional .binary.HighlyStructuredMessage displayText = 1;</code>
   * @return The displayText.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessage getDisplayText();
  /**
   * <code>optional .binary.HighlyStructuredMessage displayText = 1;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessageOrBuilder getDisplayTextOrBuilder();

  /**
   * <code>optional .binary.HighlyStructuredMessage url = 2;</code>
   * @return Whether the url field is set.
   */
  boolean hasUrl();
  /**
   * <code>optional .binary.HighlyStructuredMessage url = 2;</code>
   * @return The url.
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessage getUrl();
  /**
   * <code>optional .binary.HighlyStructuredMessage url = 2;</code>
   */
  com.xt.pfwhatsapp.ws.binary.protos.HighlyStructuredMessageOrBuilder getUrlOrBuilder();
}
